### PR TITLE
[STAR-816] Added a formula to install the piksi firmware toolchain

### PR DESCRIPTION
**Pull request by jbangelo**

### CODE REVIEW

**Comment by jbangelo** [comment]
Not sure if this would be of use. It'll be another place to change if we update the toolchain. 

FYI @silverjam @benjaminaltieri

**Review by lloydmaza — APPROVED** [review]
LGTM!
Always excited to see development in this repo.

**Comment by silverjam** [comment]
Let’s make a note of this repo in pfwp and swift-toolchains repo?

**Comment by jbangelo** [comment]
@silverjam The PFWP README suggests to use this when setting up on a Mac.

Is the firmware compiler built from swift-toolchains? I thought we were using the release from ARM.

**Comment by silverjam** [comment]
It’s just hosted there because github was more reliable than the other
hosts for automated builds.  I’m not sure where the gcc6 mac toolchain is
originally from, Michele uploaded it and didn’t record the original source.

Other toolchains were from various locations.

**Comment by silverjam** [comment]
See https://github.com/swift-nav/swift-toolchains/releases/tag/pfwp
6A88AC9C-8EF4-413F-80B1-09638B58F04A

**Pull request merged**
