### PR TITLE
Added a dependency for installing the check library

### PR DESCRIPTION
**Pull request by jbangelo**

### CODE REVIEW

**Comment by jbangelo** [comment]
Does the version number need to be bumped up?

**Comment by lloydmaza** [comment]
The Swift brew tap lives!

Was there a reason for this addition? I've seen these dependencies in other formulas, but I wasn't aware of the need for it here.

Also yeah, but the version number system is pretty lax. Up to you whether this constitutes a 1.5.0 or a 1.4.1.

**Comment by jbangelo** [comment]
Sara was running into issues getting the tests compiling on her machine and it turned out that she didn't have `check` installed. I'm not sure if this is the best way to get the check library installed as a part of the process.

**Review by lloydmaza — APPROVED** [review]
Cool, LGTM!

**Comment by jbangelo** [comment]
I'm wondering if it makes more sense to define a `clang-tools-6` formula and that installs `clang-format-6.0` and `clang-tools-6.0` and leave this `starling-toolchain` formula a meta-formula that only calls out dependencies and doesn't install anything....

**Comment by jbangelo** [comment]
I've changed some things around. I've split out the clang-tools into a separate package that pulls in the existing llvm 6 package and then adds it's own symlinks on top of it. I've also made the main `starling-toolchain` package into a sort of meta-package that lists the dependencies we need. Unfortunately homebrew doesn't officially support meta packages so I've had to use some minor work arounds, like specifying `/dev/null` as the source URL and writing a text file for the `starling-toolchain` package so it has something to install.

**Comment by jbangelo** [comment]
@lloydmaza I think this is ready to be looked at again.

**Pull request merged**
